# Generated by Django 4.2.1 on 2023-05-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('volume', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_custo', models.FloatField()),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_venda', models.FloatField()),
                ('fk_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.computador')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda_Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.itens')),
                ('fk_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Computador_Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.componente')),
                ('fk_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.computador')),
            ],
        ),
        migrations.AddField(
            model_name='computador',
            name='fk_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.modelo'),
        ),
        migrations.AddField(
            model_name='componente',
            name='fk_fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fabricante'),
        ),
        migrations.CreateModel(
            name='Armazem_Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('massa', models.FloatField()),
                ('volume', models.FloatField()),
                ('fk_armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.armazem')),
                ('fk_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.computador')),
            ],
        ),
        migrations.CreateModel(
            name='Armazem_Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('massa', models.FloatField()),
                ('volume', models.FloatField()),
                ('fk_armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.armazem')),
                ('fk_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.componente')),
            ],
        ),
    ]
