# Generated by Django 4.2.1 on 2023-05-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
